//
// Created by stephan on 18-1-2022.
//

#ifndef PROJECT_GAME_DEFINITIONS_HPP
#define PROJECT_GAME_DEFINITIONS_HPP

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define GAME_TITLE "Platformer groep 6"
#define FRAMERATE 60
#define CHARACTER_FRAME_1_FILEPATH "../img/character.jpg"

#define CHARACTER_STATE_STIL 1
#define CHARACTER_STATE_FALLING 2
#define CHARACTER_STATE_JUMPING 3

#define GRAVITY 200.0f
#define JUMPING_SPEED 200.0f
#define FLYING_SPEED 300.0f
#define JUMP_DURATION 0.50f
//#define ENABLE_SOUND
//#define ENABLE_FONT

#endif //PROJECT_GAME_DEFINITIONS_HPP