name: Auto generatate doxygen

on:
  push:
    branches: main
    paths:
      - 'Game/'
      - 'Doxyfiles'
      
  workflow_dispatch:
jobs:
       
  generate-doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: step 1 - Install doxygen
        run: sudo apt-get install doxygen
      
      - name: step 2 - Run doxygen
        run: doxygen Doxyfiles/Doxyfile
      
      - name: Commit files
        id: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Updated doxygen" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        run: git push -f origin gh_pages
